// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package database

import (
	"context"
	"time"
)

const getLatestCommentsByUser = `-- name: GetLatestCommentsByUser :many
SELECT
    c.name,
    c.comment,
    c.created_at
FROM comments c
INNER JOIN invitations i
    ON c.invitation_id = i.id
WHERE i.owner_id = $1
ORDER BY c.created_at DESC
LIMIT 5
`

type GetLatestCommentsByUserRow struct {
	Name      string
	Comment   string
	CreatedAt time.Time
}

func (q *Queries) GetLatestCommentsByUser(ctx context.Context, ownerID int32) ([]GetLatestCommentsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getLatestCommentsByUser, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLatestCommentsByUserRow
	for rows.Next() {
		var i GetLatestCommentsByUserRow
		if err := rows.Scan(&i.Name, &i.Comment, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
