// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invitation_galleries.sql

package database

import (
	"context"
	"database/sql"
)

const createInvitationGalleries = `-- name: CreateInvitationGalleries :one
INSERT INTO invitation_galleries (
    invitation_id,
    url_photo
)
VALUES (
    $1,$2
)
RETURNING id, invitation_id, url_photo
`

type CreateInvitationGalleriesParams struct {
	InvitationID int32
	UrlPhoto     sql.NullString
}

func (q *Queries) CreateInvitationGalleries(ctx context.Context, arg CreateInvitationGalleriesParams) (InvitationGallery, error) {
	row := q.db.QueryRowContext(ctx, createInvitationGalleries, arg.InvitationID, arg.UrlPhoto)
	var i InvitationGallery
	err := row.Scan(&i.ID, &i.InvitationID, &i.UrlPhoto)
	return i, err
}
