// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invitations.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO invitations (
    subdomain,
    owner_id,
    package_id,
    template_name,
    is_published,
    is_active
)
VALUES ($1,$2,$3,$4,$5,$6)
RETURNING id, subdomain, owner_id, package_id, template_name, is_published, is_active, expired_at, created_at, updated_at
`

type CreateInvitationParams struct {
	Subdomain    string
	OwnerID      int32
	PackageID    sql.NullInt32
	TemplateName sql.NullString
	IsPublished  bool
	IsActive     bool
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error) {
	row := q.db.QueryRowContext(ctx, createInvitation,
		arg.Subdomain,
		arg.OwnerID,
		arg.PackageID,
		arg.TemplateName,
		arg.IsPublished,
		arg.IsActive,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.Subdomain,
		&i.OwnerID,
		&i.PackageID,
		&i.TemplateName,
		&i.IsPublished,
		&i.IsActive,
		&i.ExpiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteInvitation = `-- name: DeleteInvitation :exec
DELETE FROM invitations
WHERE id = $1
`

func (q *Queries) DeleteInvitation(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteInvitation, id)
	return err
}

const getInvitationByID = `-- name: GetInvitationByID :one
SELECT id, subdomain, owner_id, package_id, template_name, is_published, is_active, expired_at, created_at, updated_at
FROM invitations
WHERE id = $1
`

func (q *Queries) GetInvitationByID(ctx context.Context, id int32) (Invitation, error) {
	row := q.db.QueryRowContext(ctx, getInvitationByID, id)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.Subdomain,
		&i.OwnerID,
		&i.PackageID,
		&i.TemplateName,
		&i.IsPublished,
		&i.IsActive,
		&i.ExpiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvitationBySubdomain = `-- name: GetInvitationBySubdomain :one
SELECT id, subdomain, owner_id, package_id, template_name, is_published, is_active, expired_at, created_at, updated_at
FROM invitations
WHERE subdomain = $1
`

func (q *Queries) GetInvitationBySubdomain(ctx context.Context, subdomain string) (Invitation, error) {
	row := q.db.QueryRowContext(ctx, getInvitationBySubdomain, subdomain)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.Subdomain,
		&i.OwnerID,
		&i.PackageID,
		&i.TemplateName,
		&i.IsPublished,
		&i.IsActive,
		&i.ExpiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvitationContentByID = `-- name: GetInvitationContentByID :one
SELECT id, invitation_id, title, male_name, female_name, male_nickname, female_nickname, male_parents, female_parents, url_photo_male, url_photo_female, url_photo_main, url_bg_music, url_youtube, broadcast_template, quote, created_at, updated_at
FROM invitation_contents
WHERE invitation_id = $1
`

func (q *Queries) GetInvitationContentByID(ctx context.Context, invitationID int32) (InvitationContent, error) {
	row := q.db.QueryRowContext(ctx, getInvitationContentByID, invitationID)
	var i InvitationContent
	err := row.Scan(
		&i.ID,
		&i.InvitationID,
		&i.Title,
		&i.MaleName,
		&i.FemaleName,
		&i.MaleNickname,
		&i.FemaleNickname,
		&i.MaleParents,
		&i.FemaleParents,
		&i.UrlPhotoMale,
		&i.UrlPhotoFemale,
		&i.UrlPhotoMain,
		&i.UrlBgMusic,
		&i.UrlYoutube,
		&i.BroadcastTemplate,
		&i.Quote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserInvitationByID = `-- name: GetUserInvitationByID :many
SELECT i.id, subdomain, owner_id, package_id, template_name, is_published, is_active, expired_at, i.created_at, i.updated_at, ic.id, invitation_id, title, male_name, female_name, male_nickname, female_nickname, male_parents, female_parents, url_photo_male, url_photo_female, url_photo_main, url_bg_music, url_youtube, broadcast_template, quote, ic.created_at, ic.updated_at
FROM invitations i
LEFT JOIN invitation_contents ic
    ON i.id = ic.invitation_id
WHERE i.owner_id = $1
`

type GetUserInvitationByIDRow struct {
	ID                int32
	Subdomain         string
	OwnerID           int32
	PackageID         sql.NullInt32
	TemplateName      sql.NullString
	IsPublished       bool
	IsActive          bool
	ExpiredAt         time.Time
	CreatedAt         time.Time
	UpdatedAt         time.Time
	ID_2              sql.NullInt32
	InvitationID      sql.NullInt32
	Title             sql.NullString
	MaleName          sql.NullString
	FemaleName        sql.NullString
	MaleNickname      sql.NullString
	FemaleNickname    sql.NullString
	MaleParents       sql.NullString
	FemaleParents     sql.NullString
	UrlPhotoMale      sql.NullString
	UrlPhotoFemale    sql.NullString
	UrlPhotoMain      sql.NullString
	UrlBgMusic        sql.NullString
	UrlYoutube        sql.NullString
	BroadcastTemplate sql.NullString
	Quote             sql.NullString
	CreatedAt_2       sql.NullTime
	UpdatedAt_2       sql.NullTime
}

func (q *Queries) GetUserInvitationByID(ctx context.Context, ownerID int32) ([]GetUserInvitationByIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserInvitationByID, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserInvitationByIDRow
	for rows.Next() {
		var i GetUserInvitationByIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Subdomain,
			&i.OwnerID,
			&i.PackageID,
			&i.TemplateName,
			&i.IsPublished,
			&i.IsActive,
			&i.ExpiredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ID_2,
			&i.InvitationID,
			&i.Title,
			&i.MaleName,
			&i.FemaleName,
			&i.MaleNickname,
			&i.FemaleNickname,
			&i.MaleParents,
			&i.FemaleParents,
			&i.UrlPhotoMale,
			&i.UrlPhotoFemale,
			&i.UrlPhotoMain,
			&i.UrlBgMusic,
			&i.UrlYoutube,
			&i.BroadcastTemplate,
			&i.Quote,
			&i.CreatedAt_2,
			&i.UpdatedAt_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInvitation = `-- name: UpdateInvitation :one
UPDATE invitations
SET
    subdomain = $2,
    package_id = $3,
    template_name = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, subdomain, owner_id, package_id, template_name, is_published, is_active, expired_at, created_at, updated_at
`

type UpdateInvitationParams struct {
	ID           int32
	Subdomain    string
	PackageID    sql.NullInt32
	TemplateName sql.NullString
}

func (q *Queries) UpdateInvitation(ctx context.Context, arg UpdateInvitationParams) (Invitation, error) {
	row := q.db.QueryRowContext(ctx, updateInvitation,
		arg.ID,
		arg.Subdomain,
		arg.PackageID,
		arg.TemplateName,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.Subdomain,
		&i.OwnerID,
		&i.PackageID,
		&i.TemplateName,
		&i.IsPublished,
		&i.IsActive,
		&i.ExpiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
