// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invitation_contents.sql

package database

import (
	"context"
	"database/sql"
)

const createInvitationContent = `-- name: CreateInvitationContent :one
INSERT INTO invitation_contents (
    invitation_id,
    title,
    male_name,
    female_name,
    male_nickname,
    female_nickname,
    male_parents,
    female_parents,
    url_photo_male,
    url_photo_female,
    url_photo_main,
    url_bg_music,
    url_youtube
)
VALUES (
    $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13
)
RETURNING id, invitation_id, title, male_name, female_name, male_nickname, female_nickname, male_parents, female_parents, url_photo_male, url_photo_female, url_photo_main, url_bg_music, url_youtube, broadcast_template, quote, created_at, updated_at
`

type CreateInvitationContentParams struct {
	InvitationID   int32
	Title          string
	MaleName       string
	FemaleName     string
	MaleNickname   sql.NullString
	FemaleNickname sql.NullString
	MaleParents    sql.NullString
	FemaleParents  sql.NullString
	UrlPhotoMale   sql.NullString
	UrlPhotoFemale sql.NullString
	UrlPhotoMain   sql.NullString
	UrlBgMusic     sql.NullString
	UrlYoutube     sql.NullString
}

func (q *Queries) CreateInvitationContent(ctx context.Context, arg CreateInvitationContentParams) (InvitationContent, error) {
	row := q.db.QueryRowContext(ctx, createInvitationContent,
		arg.InvitationID,
		arg.Title,
		arg.MaleName,
		arg.FemaleName,
		arg.MaleNickname,
		arg.FemaleNickname,
		arg.MaleParents,
		arg.FemaleParents,
		arg.UrlPhotoMale,
		arg.UrlPhotoFemale,
		arg.UrlPhotoMain,
		arg.UrlBgMusic,
		arg.UrlYoutube,
	)
	var i InvitationContent
	err := row.Scan(
		&i.ID,
		&i.InvitationID,
		&i.Title,
		&i.MaleName,
		&i.FemaleName,
		&i.MaleNickname,
		&i.FemaleNickname,
		&i.MaleParents,
		&i.FemaleParents,
		&i.UrlPhotoMale,
		&i.UrlPhotoFemale,
		&i.UrlPhotoMain,
		&i.UrlBgMusic,
		&i.UrlYoutube,
		&i.BroadcastTemplate,
		&i.Quote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateInvitationContent = `-- name: UpdateInvitationContent :one
UPDATE invitation_contents
SET
    title =$2,
    male_name =$3,
    female_name =$4,
    male_nickname =$5,
    female_nickname =$6,
    male_parents =$7,
    female_parents =$8,
    url_photo_male =$9,
    url_photo_female =$10,
    url_photo_main =$11,
    url_bg_music =$12,
    url_youtube =$13,
    updated_at = NOW()
WHERE invitation_id = $1
RETURNING id, invitation_id, title, male_name, female_name, male_nickname, female_nickname, male_parents, female_parents, url_photo_male, url_photo_female, url_photo_main, url_bg_music, url_youtube, broadcast_template, quote, created_at, updated_at
`

type UpdateInvitationContentParams struct {
	InvitationID   int32
	Title          string
	MaleName       string
	FemaleName     string
	MaleNickname   sql.NullString
	FemaleNickname sql.NullString
	MaleParents    sql.NullString
	FemaleParents  sql.NullString
	UrlPhotoMale   sql.NullString
	UrlPhotoFemale sql.NullString
	UrlPhotoMain   sql.NullString
	UrlBgMusic     sql.NullString
	UrlYoutube     sql.NullString
}

func (q *Queries) UpdateInvitationContent(ctx context.Context, arg UpdateInvitationContentParams) (InvitationContent, error) {
	row := q.db.QueryRowContext(ctx, updateInvitationContent,
		arg.InvitationID,
		arg.Title,
		arg.MaleName,
		arg.FemaleName,
		arg.MaleNickname,
		arg.FemaleNickname,
		arg.MaleParents,
		arg.FemaleParents,
		arg.UrlPhotoMale,
		arg.UrlPhotoFemale,
		arg.UrlPhotoMain,
		arg.UrlBgMusic,
		arg.UrlYoutube,
	)
	var i InvitationContent
	err := row.Scan(
		&i.ID,
		&i.InvitationID,
		&i.Title,
		&i.MaleName,
		&i.FemaleName,
		&i.MaleNickname,
		&i.FemaleNickname,
		&i.MaleParents,
		&i.FemaleParents,
		&i.UrlPhotoMale,
		&i.UrlPhotoFemale,
		&i.UrlPhotoMain,
		&i.UrlBgMusic,
		&i.UrlYoutube,
		&i.BroadcastTemplate,
		&i.Quote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
