// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invoices.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO invoices (
    user_id,
    invitation_id,
    total_price,
    payment_due_date,
    status
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, user_id, invitation_id, total_price, payment_due_date, is_paid, receipt_proof, meta, confirmed_at, created_at, updated_at, status
`

type CreateInvoiceParams struct {
	UserID         sql.NullInt32
	InvitationID   sql.NullInt32
	TotalPrice     int32
	PaymentDueDate time.Time
	Status         string
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRowContext(ctx, createInvoice,
		arg.UserID,
		arg.InvitationID,
		arg.TotalPrice,
		arg.PaymentDueDate,
		arg.Status,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InvitationID,
		&i.TotalPrice,
		&i.PaymentDueDate,
		&i.IsPaid,
		&i.ReceiptProof,
		&i.Meta,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
	)
	return i, err
}

const getInvoiceByID = `-- name: GetInvoiceByID :one

SELECT id, user_id, invitation_id, total_price, payment_due_date, is_paid, receipt_proof, meta, confirmed_at, created_at, updated_at, status
FROM invoices
WHERE id = $1
`

func (q *Queries) GetInvoiceByID(ctx context.Context, id int32) (Invoice, error) {
	row := q.db.QueryRowContext(ctx, getInvoiceByID, id)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InvitationID,
		&i.TotalPrice,
		&i.PaymentDueDate,
		&i.IsPaid,
		&i.ReceiptProof,
		&i.Meta,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
	)
	return i, err
}

const getInvoicesByInvitationID = `-- name: GetInvoicesByInvitationID :one

SELECT id, user_id, invitation_id, total_price, payment_due_date, is_paid, receipt_proof, meta, confirmed_at, created_at, updated_at, status
FROM invoices
WHERE invitation_id = $1
`

func (q *Queries) GetInvoicesByInvitationID(ctx context.Context, invitationID sql.NullInt32) (Invoice, error) {
	row := q.db.QueryRowContext(ctx, getInvoicesByInvitationID, invitationID)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InvitationID,
		&i.TotalPrice,
		&i.PaymentDueDate,
		&i.IsPaid,
		&i.ReceiptProof,
		&i.Meta,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
	)
	return i, err
}

const getInvoicesByUserID = `-- name: GetInvoicesByUserID :many

SELECT
    i.id,
    i.invitation_id,
    i.created_at,
    i.total_price,
    i.payment_due_date,
    i.is_paid,
    i.receipt_proof,
    i.status,
    inv.subdomain,
    inv.template_name
FROM invoices i
JOIN invitations inv
    ON inv.id = i.invitation_id
WHERE i.user_id = $1
ORDER BY i.created_at DESC
`

type GetInvoicesByUserIDRow struct {
	ID             int32
	InvitationID   sql.NullInt32
	CreatedAt      time.Time
	TotalPrice     int32
	PaymentDueDate time.Time
	IsPaid         bool
	ReceiptProof   sql.NullString
	Status         string
	Subdomain      string
	TemplateName   sql.NullString
}

func (q *Queries) GetInvoicesByUserID(ctx context.Context, userID sql.NullInt32) ([]GetInvoicesByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getInvoicesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetInvoicesByUserIDRow
	for rows.Next() {
		var i GetInvoicesByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.InvitationID,
			&i.CreatedAt,
			&i.TotalPrice,
			&i.PaymentDueDate,
			&i.IsPaid,
			&i.ReceiptProof,
			&i.Status,
			&i.Subdomain,
			&i.TemplateName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInvoicePaymentStatus = `-- name: UpdateInvoicePaymentStatus :exec

UPDATE invoices
SET
    status = $2,
    is_paid = $3,
    confirmed_at = $4,
    meta = $5,
    updated_at = NOW()
WHERE id = $1
`

type UpdateInvoicePaymentStatusParams struct {
	ID          int32
	Status      string
	IsPaid      bool
	ConfirmedAt sql.NullTime
	Meta        sql.NullString
}

func (q *Queries) UpdateInvoicePaymentStatus(ctx context.Context, arg UpdateInvoicePaymentStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateInvoicePaymentStatus,
		arg.ID,
		arg.Status,
		arg.IsPaid,
		arg.ConfirmedAt,
		arg.Meta,
	)
	return err
}
