// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type UserRole string

const (
	UserRoleUser  UserRole = "user"
	UserRoleAdmin UserRole = "admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Comment struct {
	ID           int32
	InvitationID int32
	Name         string
	Comment      string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Guest struct {
	ID           int32
	InvitationID int32
	Name         string
	Code         string
	Email        sql.NullString
	WaNumber     sql.NullString
	Address      sql.NullString
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Invitation struct {
	ID           int32
	Subdomain    string
	OwnerID      int32
	PackageID    sql.NullInt32
	TemplateName sql.NullString
	IsPublished  bool
	IsActive     bool
	ExpiredAt    time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type InvitationContent struct {
	ID                int32
	InvitationID      int32
	Title             string
	MaleName          string
	FemaleName        string
	MaleNickname      sql.NullString
	FemaleNickname    sql.NullString
	MaleParents       sql.NullString
	FemaleParents     sql.NullString
	UrlPhotoMale      sql.NullString
	UrlPhotoFemale    sql.NullString
	UrlPhotoMain      sql.NullString
	UrlBgMusic        sql.NullString
	UrlYoutube        sql.NullString
	BroadcastTemplate sql.NullString
	Quote             sql.NullString
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type InvitationGallery struct {
	ID           int32
	InvitationID int32
	UrlPhoto     sql.NullString
}

type InvitationSubevent struct {
	ID                 int32
	InvitationID       int32
	Name               string
	LocationName       string
	LocationAddress    sql.NullString
	LocationCoordinate sql.NullString
	TimeStart          time.Time
	TimeEnd            time.Time
	IsPrimary          bool
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type Invoice struct {
	ID             int32
	UserID         sql.NullInt32
	InvitationID   sql.NullInt32
	TotalPrice     int32
	PaymentDueDate time.Time
	IsPaid         bool
	ReceiptProof   sql.NullString
	Meta           sql.NullString
	ConfirmedAt    sql.NullTime
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Package struct {
	ID                int32
	Name              string
	Price             int32
	Description       sql.NullString
	Duration          int32
	MaxEvent          int32
	MaxGuest          int32
	MaxComment        int32
	MaxGallery        int32
	YoutubeLink       bool
	BroadcastTemplate bool
	MusicBackground   bool
	Quote             bool
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type ResetToken struct {
	ID        int32
	UserID    int32
	Token     string
	ExpiredAt time.Time
}

type Session struct {
	SessionID string
	Expires   sql.NullTime
	Data      sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID         int32
	Email      string
	Password   string
	Name       string
	Role       UserRole
	Phone      sql.NullString
	IsVerified bool
	Photo      sql.NullString
	CreatedAt  time.Time
	UpdatedAt  time.Time
	ApiKey     string
}

type View struct {
	ID           int32
	InvitationID int32
	Date         time.Time
	City         sql.NullString
}
