// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: packages.sql

package database

import (
	"context"
	"database/sql"
)

const createPackage = `-- name: CreatePackage :one
INSERT INTO packages (
    name,
    price,
    description
) VALUES (
    $1, $2, $3
)
RETURNING id, name, price, description, duration, max_event, max_guest, max_comment, max_gallery, youtube_link, broadcast_template, music_background, quote, created_at, updated_at
`

type CreatePackageParams struct {
	Name        string
	Price       int32
	Description sql.NullString
}

func (q *Queries) CreatePackage(ctx context.Context, arg CreatePackageParams) (Package, error) {
	row := q.db.QueryRowContext(ctx, createPackage, arg.Name, arg.Price, arg.Description)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.Description,
		&i.Duration,
		&i.MaxEvent,
		&i.MaxGuest,
		&i.MaxComment,
		&i.MaxGallery,
		&i.YoutubeLink,
		&i.BroadcastTemplate,
		&i.MusicBackground,
		&i.Quote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPackageByID = `-- name: GetPackageByID :one
SELECT id, name, price, description, duration, max_event, max_guest, max_comment, max_gallery, youtube_link, broadcast_template, music_background, quote, created_at, updated_at
FROM packages
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetPackageByID(ctx context.Context, id int32) (Package, error) {
	row := q.db.QueryRowContext(ctx, getPackageByID, id)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.Description,
		&i.Duration,
		&i.MaxEvent,
		&i.MaxGuest,
		&i.MaxComment,
		&i.MaxGallery,
		&i.YoutubeLink,
		&i.BroadcastTemplate,
		&i.MusicBackground,
		&i.Quote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPackages = `-- name: ListPackages :many
SELECT id, name, price, description, duration, max_event, max_guest, max_comment, max_gallery, youtube_link, broadcast_template, music_background, quote, created_at, updated_at
FROM packages
ORDER BY id
`

func (q *Queries) ListPackages(ctx context.Context) ([]Package, error) {
	rows, err := q.db.QueryContext(ctx, listPackages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Package
	for rows.Next() {
		var i Package
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.Description,
			&i.Duration,
			&i.MaxEvent,
			&i.MaxGuest,
			&i.MaxComment,
			&i.MaxGallery,
			&i.YoutubeLink,
			&i.BroadcastTemplate,
			&i.MusicBackground,
			&i.Quote,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
