// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const getCityStatsByUser = `-- name: GetCityStatsByUser :many
SELECT
    v.city,
    COUNT(*) AS total
FROM views v
INNER JOIN invitations i
    ON v.invitation_id = i.id
WHERE i.owner_id = $1
AND v.city IS NOT NULL
GROUP BY v.city
ORDER BY total DESC
`

type GetCityStatsByUserRow struct {
	City  sql.NullString
	Total int64
}

func (q *Queries) GetCityStatsByUser(ctx context.Context, ownerID int32) ([]GetCityStatsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getCityStatsByUser, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCityStatsByUserRow
	for rows.Next() {
		var i GetCityStatsByUserRow
		if err := rows.Scan(&i.City, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailyViewsByUser = `-- name: GetDailyViewsByUser :many

SELECT 
    i.subdomain,
    DATE(v.date) as view_date,
    COUNT(*) as count
FROM views v
JOIN invitations i
    ON i.id = v.invitation_id
WHERE 
    i.owner_id = $1
    AND v.date >= $2
    AND v.date <= $3
GROUP BY i.subdomain, DATE(v.date)
ORDER BY view_date
`

type GetDailyViewsByUserParams struct {
	OwnerID int32
	Date    time.Time
	Date_2  time.Time
}

type GetDailyViewsByUserRow struct {
	Subdomain string
	ViewDate  time.Time
	Count     int64
}

func (q *Queries) GetDailyViewsByUser(ctx context.Context, arg GetDailyViewsByUserParams) ([]GetDailyViewsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getDailyViewsByUser, arg.OwnerID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDailyViewsByUserRow
	for rows.Next() {
		var i GetDailyViewsByUserRow
		if err := rows.Scan(&i.Subdomain, &i.ViewDate, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalCommentsByUser = `-- name: GetTotalCommentsByUser :one
SELECT COUNT(c.id)
FROM comments c
INNER JOIN invitations i
    ON c.invitation_id = i.id
WHERE i.owner_id = $1
`

func (q *Queries) GetTotalCommentsByUser(ctx context.Context, ownerID int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalCommentsByUser, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTotalGuests = `-- name: GetTotalGuests :one
SELECT COUNT(g.id)
FROM guests g
INNER JOIN invitations i
    ON g.invitation_id = i.id 
WHERE i.owner_id = $1
`

func (q *Queries) GetTotalGuests(ctx context.Context, ownerID int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalGuests, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTotalInvitations = `-- name: GetTotalInvitations :one
SELECT COUNT(id)
FROM invitations
WHERE owner_id = $1
`

func (q *Queries) GetTotalInvitations(ctx context.Context, ownerID int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalInvitations, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTotalViews = `-- name: GetTotalViews :one
SELECT COUNT(v.id)
FROM views v
INNER JOIN invitations i
    ON v.invitation_id = i.id
WHERE i.owner_id = $1
`

func (q *Queries) GetTotalViews(ctx context.Context, ownerID int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalViews, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
